DauGiaTrucTuyen/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DauGiaTrucTuyen.DataBinding;
using DauGiaTrucTuyen.Data;
using DauGiaTrucTuyen.IDataBinding;

namespace DauGiaTrucTuyen.Controllers
{

    public class CategoryController : Controller
    {
        private Db_DauGiaTrucTuyen db = new Db_DauGiaTrucTuyen();

        private readonly ICategory _iCategory;

        public CategoryController() : this(new CategoryService())
        {
        }

        public CategoryController(ICategory iCategory)
        {
            _iCategory = iCategory;
        }

        //Trả về danh mục sản phẩm ra slide bar
        public ActionResult GetCategorySideBar()
        {
            return PartialView(_iCategory.GetListCategoryForClient());
        }

        //Trả về danh mục sản phẩm ra footer
        public ActionResult GetCategoryFooter()
        {
            return PartialView(_iCategory.GetListCategoryForClient());
        }
    }
}

DauGiaTrucTuyen/Controllers/ManagerAuctionController.cs
using DauGiaTrucTuyen.Areas.Admin.Models;
using DauGiaTrucTuyen.Data;
using DauGiaTrucTuyen.DataBinding;
using DauGiaTrucTuyen.IDataBinding;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace DauGiaTrucTuyen.Controllers
{
    [Authorize]
    public class ManagerAuctionController : Controller
    {
        private Db_DauGiaTrucTuyen db = new Db_DauGiaTrucTuyen();
        private readonly IProduct _iProduct;

        public ManagerAuctionController() : this(new ProductService())
        {
        }

        public ManagerAuctionController(IProduct product)
        {
            _iProduct = product;
        }

        // GET: ManagerAuction
        public ActionResult Index()
        {
            return View(_iProduct.GetListProductForClient(User.Identity.GetUserId()));
        }

        public bool EndAuction(string productId)
        {
            if (_iProduct.EndAuction(productId))
                return true;
            return false;
        }

        //Tạo mới sản phẩm (GET)
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Category_Id = new SelectList(db.Categorys, "Categorys_Id", "CategoryName");
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "1:00 s", Value = "600000000" });
            items.Add(new SelectListItem { Text = "3:00 s", Value = "1800000000" });
            items.Add(new SelectListItem { Text = "5:00 s", Value = "3000000000" });
            items.Add(new SelectListItem { Text = "10:00 s", Value = "6000000000" });
            items.Add(new SelectListItem { Text = "30:00 s", Value = "18000000000" });
            items.Add(new SelectListItem { Text = "1:00:00 s", Value = "36000000000" });
            items.Add(new SelectListItem { Text = "2:00:00 s", Value = "72000000000" });
            items.Add(new SelectListItem { Text = "4:00:00 s", Value = "144000000000" });
            items.Add(new SelectListItem { Text = "8:00:00 s", Value = "288000000000" });
            items.Add(new SelectListItem { Text = "12:00:00 s", Value = "432000000000" });
            items.Add(new SelectListItem { Text = "24:00:00 s", Value = "863999999999" });
            ViewBag.SelectedItems = items;
            return View();
        }

        //Tạo mới sản phẩm (POST)
        [HttpPost]
        public ActionResult Create(AddProductViewModel model, HttpPostedFileBase file, HttpPostedFileBase file1, HttpPostedFileBase file2)
        {
            //model.Image = file.ToString();
            if (ModelState.IsValid)
            {
                if (_iProduct.CreateForClient(model, file, file1, file2, User.Identity.GetUserId()))
                    return RedirectToAction("ConfirmAddProduct");
                return HttpNotFound();
            }
            else
            {
                ViewBag.Category_Id = new SelectList(db.Categorys, "Categorys_Id", "CategoryName");
                return View(model);
            }
        }

        [AllowAnonymous]
        public ActionResult Edit(string id)
        {
            ViewBag.Category_Id = new SelectList(db.Categorys, "Categorys_Id", "CategoryName");
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "1:00 s", Value = "600000000" });
            items.Add(new SelectListItem { Text = "3:00 s", Value = "1800000000" });
            items.Add(new SelectListItem { Text = "5:00 s", Value = "3000000000" });
            items.Add(new SelectListItem { Text = "10:00 s", Value = "6000000000" });
            items.Add(new SelectListItem { Text = "30:00 s", Value = "18000000000" });
            items.Add(new SelectListItem { Text = "1:00:00 s", Value = "36000000000" });
            items.Add(new SelectListItem { Text = "2:00:00 s", Value = "72000000000" });
            items.Add(new SelectListItem { Text = "4:00:00 s", Value = "144000000000" });
            ViewBag.SelectedItems = items;
            var result = _iProduct.GetViewEditProduct(id);
            return View(result);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Edit(EditProductViewModel model, HttpPostedFileBase file, HttpPostedFileBase file1, HttpPostedFileBase file2)
        {
            if (ModelState.IsValid)
            {
                _iProduct.Edit(model, file, file1, file2);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Detail(string id)
        {
            var result = _iProduct.DetailProduct(id);
            if (result != null)
                return View(result);
            return HttpNotFound();
        }

        public ActionResult MailContent()
        {
            return View();
        }

        public ActionResult MailContentForUserAdd()
        {
            return View();
        }

        public ActionResult ConfirmAddProduct()
        {
            return View();
        }
    }
}

DauGiaTrucTuyen/Controllers/MyAuctionController.cs
using DauGiaTrucTuyen.DataBinding;
using DauGiaTrucTuyen.IDataBinding;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;

namespace DauGiaTrucTuyen.Controllers
{
    [Authorize]
    public class MyAuctionController : Controller
    {
        private readonly IMyAuction _iMyAuction;
        public MyAuctionController() : this(new MyAuctionService())
        {

        }

        public MyAuctionController(MyAuctionService myAuctionService)
        {
            _iMyAuction = myAuctionService;
        }

        public ActionResult Auctioning()
        {
            return View(_iMyAuction.ListAuctioning(User.Identity.GetUserId()));
        }

        public ActionResult AuctionWin()
        {
            return View(_iMyAuction.ListAuctionWin(User.Identity.GetUserId()));
        }

        public ActionResult AuctionLost()
        {
            return View(_iMyAuction.ListAuctionLost(User.Identity.GetUserId()));
        }

        public ActionResult FeedBack(string productId)
        {
            ViewBag.ProductId = productId;
            return View();
        }

        public bool ConfirmTransactioned(string productId)
        {
            if (_iMyAuction.ConfirmTransaction(productId))
                return true;
            return false;
        }
    }
}

DauGiaTrucTuyen/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using DauGiaTrucTuyen.Areas.Admin.Models;
using DauGiaTrucTuyen.Data;
using DauGiaTrucTuyen.DataBinding;
using DauGiaTrucTuyen.IDataBinding;

namespace DauGiaTrucTuyen.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private Db_DauGiaTrucTuyen db = new Db_DauGiaTrucTuyen();

        private readonly IReport _iReport;

        public ReportsController() : this(new ReportService())
        {

        }

        public ReportsController(IReport report)
        {
            _iReport = report;
        }

        // GET: Reports/Create
        public ActionResult Create()
        {
            ViewBag.Message = null;
            return View();
        }
        
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AddReportViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (_iReport.AddReport(model, User.Identity.GetUserId()))
                    return RedirectToAction("ConfirmCreateReport");
            }
            return View(model);
        }

        public ActionResult ConfirmCreateReport()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DauGiaTrucTuyen/Views/Shared/_LayoutClient.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title - Đấu Giá Trực Tuyến</title>
    <link href="~/Content/ClientTemplate/images/img_452250.png" type="image/png" rel="shortcut icon" />
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Electronic Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
	SmartPhone Compatible web template, free web designs for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <!-- Custom Theme files -->
    <link href="~/Content/ClientTemplate/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/ClientTemplate/css/style.css" rel="stylesheet" />
    <link href="~/Content/ClientTemplate/css/fasthover.css" rel="stylesheet" />
    <link href="~/Content/ClientTemplate/css/popuo-box.css" rel="stylesheet" />
    <!-- Sweetalert  CSS-->
    <link href="~/Content/Admin/sweetalert/css/sweetalert.css" rel="stylesheet" />
    <!-- //Custom Theme files -->
    <!-- Custom Theme files -->
    <link href="~/Content/ClientTemplate/css/loadpage.css" rel="stylesheet" />
    <!-- Font Awesome 5.5.0 -->
    <link href="~/Content/Admin/bower_components/font-awesome/css/all.css" rel="stylesheet" />
    <!-- Css chatbox -->
    <link href="~/Content/ClientTemplate/css/chatbox/chatbox.css" rel="stylesheet" />
    <!-- //font-awesome icons -->
    @RenderSection("css", required: false)
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <!-- header -->
    <div class="header" id="home1">
        <div class="container row" style="margin: auto">
            <div class="col-md-2 col-sm-0"></div>
            <div class="col-md-8 col-sm-12 w3l_logo">
                <h1><a href="@Url.Action("Index","Home")">ĐẤU GIÁ TRỰC TUYẾN<span>Duy Tan University</span></a></h1>
            </div>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
    <!-- navigation -->
    <div class="navigation">
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="navbar-header nav_2">
                    <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("Index","Home")" class="act">Trang chủ</a></li>
                        <li class="w3pages">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Danh mục <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @{Html.RenderAction("GetCategorySideBar", "Category", new { area = "" }); }
                            </ul>
                        </li>
                        <li><a href="@Url.Action("Create","Reports")">Báo cáo người dùng</a></li>
                        <li><a href="@Url.Action("Auctioning","MyAuction")">Lịch sử đấu giá</a></li>
                        <li><a href="@Url.Action("Index","ManagerAuction")">Quản lý đấu giá</a></li>
                        <li><a href="#footer-croll" class="contact">Liên hệ</a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <!-- content -->
    <div class="banner-bottom">
        <div class="container">
            <div class="wthree_banner_bottom_right">
                <div class="tab-pane fade active in" id="home" aria-labelledby="home-tab">
                    <div class="agile_ecommerce_tabs">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- load ngay gio -->
    <div class="newsletter">
        <div class="container">
            <div class="col-md-12 w3agile_newsletter_left">
                <marquee><i id="js-load-ngaygio"></i></marquee>
            </div>
        </div>
    </div>
    <!-- //newsletter -->
    <!-- footer -->
    <div class="footer" id="footer-croll">
        <div class="container">
            <div class="w3_footer_grids">
                <div class="col-md-3 w3_footer_grid">
                    <h3>Liên hệ</h3>
                    <p>Nhóm sinh viên Đại Học Duy Tân</p>
                    <ul class="address">
                        <li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>K7/25 Quang Trung<span>Tp. Đà Nẵng</span></li>
                        <li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="#">doanthanhlong1801@gmail.com</a></li>
                        <li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>+1234 567 567</li>
                    </ul>
                </div>
                <div class="col-md-3 w3_footer_grid">
                    <h3>Thông tin</h3>
                    <ul class="info">
                        <li><a href="@Url.Action("SecurityView","Home")">Chính sách bảo mật</a></li>
                        <li><a href="#">Hướng dẫn giao dịch</a></li>
                        <li><a href="@Url.Action("Policy","Home")">Chính sách trả phí</a></li>
                    </ul>
                </div>
                <div class="col-md-3 w3_footer_grid">
                    <h3>DANH MỤC</h3>
                    <ul class="info">
                        @{Html.RenderAction("GetCategoryFooter", "Category", new { area = "" }); }
                    </ul>
                </div>
                <div class="col-md-3 w3_footer_grid">
                    <h3>Menu</h3>
                    <ul class="info">
                        <li><a href="@Url.Action("Index","Home")">Trang chủ</a></li>
                        <li><a href="@Url.Action("Create","Reports")">Báo cáo người dùng</a></li>
                        <li><a href="@Url.Action("Auctioning","MyAuction")">Lịch sử đấu giá</a></li>
                        <li><a href="@Url.Action("Index","ManagerAuction")">Quản lý đấu giá</a></li>
                    </ul>
                    <h4>Theo dõi chúng tôi</h4>
                    <div class="agileits_social_button">
                        <ul>
                            <li><a href="#" class="facebook"> </a></li>
                            <li><a href="#" class="google"> </a></li>
                        </ul>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="footer-copy">
            <div class="footer-copy1">
                <div class="footer-copy-pos">
                    <a href="#home1" class="scroll"><img src="~/Content/ClientTemplate/images/arrow.png" alt=" " class="img-responsive" /></a>
                </div>
            </div>
            <div class="container">
                <p>&copy; Bản quyền thuộc nhóm sinh viên Đại Học Duy Tân | Design by <a href="https://www.facebook.com/thanhlong1801">Thanh Long</a></p>
            </div>
        </div>
    </div>
    <!--chatbox-->
    <div class="row">
        <div class="chatbox chatbox-tray">
            <div class="chatbox-title" value="">
                <img id="lazo-button" src="~/Content/ClientTemplate/images/img-chatbox/Group 42.png" />
                <span>Trò chuyện ngay với chúng tôi</span>
            </div>
            <form class="customer-info">
                <p>Vùi lòng nhập Email</p>
                <input type="email" placeholder="Email" class="form-control mx-auto" required />
                <input type="hidden" id="txtNameEmail" name="name" value="" />
                <button id="btnCus" type="submit" class="btn btn-primary mt-2" value="submit">Bắt đầu cuộc trò chuyện</button>
            </form>
            <div class="chatbox-body">
                <ul class="chatbox-body-msg list-unstyled">
                    <li class="float-left mt-1 chatbox-body-msg-left">
                        Xin chào. Bạn cần tư vấn gì...
                    </li>
                </ul>
            </div>
            <div class="chatbox-footer">
                <div class="chatbox-footer-content">
                    <textarea type="text" name="name" id="txtMsg" placeholder="Nhập tin nhắn..."></textarea>
                    <button id="btn-Send">
                        <img src="~/Content/ClientTemplate/images/img-chatbox/send.png" />
                    </button>
                </div>
            </div>
        </div>
        <div class="chatbox-button">
        </div>

    </div>
    <!-- //footer -->
    @*<script src="~/Scripts/jquery-3.3.1.js"></script>*@
    <script src="~/Content/ClientTemplate/js/jquery-2.2.3.min.js"></script>
    <!-- scrolling -->
    <script src="~/Content/ClientTemplate/js/scroll.js"></script>
    <!-- load ngay gio -->
    <script src="~/Content/ClientTemplate/js/jsNgayGio.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <!-- Js RealTime-Hub-->
    <script src="~/Scripts/jquery.signalR-2.2.2.js"></script>
    <script src="~/signalr/hubs"></script>
    <!-- Sweetalert JS -->
    <script src="~/Content/Admin/sweetalert/js/sweetalert.min.js"></script>
    <!-- Load page -->
    <script src="~/Content/ClientTemplate/js/loadpage.js"></script>
    @RenderSection("scripts", required: false)
    <!-- Upload img JS -->
    <script src="~/Content/ClientTemplate/js/upload-img.js"></script>
    <!-- Validation Js -->
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @Scripts.Render("~/bundles/ckeditor")
    <script src="~/Scripts/ckfinder/ckfinder.js"></script>
    <script>
        var isAuthenticated = "@Request.IsAuthenticated" == "True";
        if (!isAuthenticated) {
            $(".customer-info").html('<a href="@Url.Action("Login","Account")">Vui lòng đăng nhập để trò chuyện</a>')
            var userIdAll = '';
        }
        else {
            if ('@User.Identity.GetUserName()' == "admin@gmail.com") {
                $(".chatbox").css("display", "none")
                $(".chatbox-button").css("display", "none")
                var userIdAll = "";
            }
            else {
                var userIdAll = "@User.Identity.GetUserId()";
            }
        }
    </script>
    <script src="~/Scripts/chatbox/chatbox.js"></script>
</body>
</html>